name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: quick-adb-${{ runner.os }}
          path: |
            build/quick-adb
            build/Release/quick-adb.exe
